spring:
  application:
    name: microservice-consumer-ribbon-properties
server:
  port: 8183
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
microservice-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule